### ISSUE TITLE
Mistake in waitForTaskToFinish

### ISSUE THREAD

**Issue by ferdl9999** [Corsinvest/cv4pve-api-java#6]
In line 476, class PveClientBase, there is the following condition in the method waitForTaskToFinish:
`while (isRunning && (timeStart - System.currentTimeMillis()) < timeOut)`

After a timeout, the `(timeStart - System.currentTimeMillis()) < timeOut` condition should be false.
But this condition is never false, because timeStart - System.currentTimeMillis() is always negative and less than a positive timeout.

Right condition would be: `(System.currentTimeMillis() - timeStart) < timeOut`
Condition must also get corrected in the last line of this method.

Please correct me if i am wrong

// Edit: Maybe it would be better to return a boolean instead of an int. 'false' for timeout exceeded, 'true' for task finished in a time less than timeout

**Comment by franklupo** [comment]
Hi,
thank you for your suggestion. I'm preparing Fix.

Best regards
