### ISSUE TITLE
Parameter verification failed when configuring network devices for lxc / qemu

### ISSUE THREAD

**Issue by ferdl9999** [Corsinvest/cv4pve-api-java#7]
Hello,

i have a problem with configuring network devices via your api on lxc creation (and also qemu creation using cloudinit). Maybe i am doing something wrong, but maybe there is some internal problem in your api?

Basically, i have the following code:

``Map<Integer, String> netN = new HashMap<>();
netN.put(0, "name=eth0,rate=15,bridge=vmbr0,firewall=1,gw=xx.xx.xx.xx,ip=xx.xx.xx.xx/24,hwaddr=02:00:be:0f:f2:63");``

The netN map i am passing to the getLxc().createVm function.
I also tried it with only passing the name field ("name=eth0"). Am i doing something wrong? 

I am also using your PHP api and there are no problems.

Here is the output of the debug messages, the net0 string is normally right, using the same in your php api:
`Parameters:
net0 : name=eth0,rate=15,bridge=vmbr0,firewall=1,gw=xx.xx.xx.xx,ip=xx.xx.xx.xx/24,hwaddr=02:00:be:0f:f2:63
memory : 1024
cpulimit : 1
ostemplate : local:vztmpl/debian-10.0-x86_64.tar.gz
hostname : test
password : test
cores : 1
vmid : 289
swap : 512
start : 1
unprivileged : 1
onboot : 1
rootfs : disk1:50
arch : amd64`

I always get the following result:
StatusCode:          400
ReasonPhrase:        Parameter verification failed.
IsSuccessStatusCode: false

**Comment by franklupo** [comment]
Hi,
can enable debug using **client,setDebugLevel(99)** and attach output?
Remeber remove password from output

Best regards

**Comment by ferdl9999** [comment]
Hi,
i had debug level 2 but i have increased it to 99.

Here is the output: https://pastebin.com/2rcUUQEQ

I have just passed parameter "name=eth0" to the netN map as string

**Comment by franklupo** [comment]
execute with complete string "name=eth0,rate=15,bridge=vmbr0,firewall=1,gw=xx.xx.xx.xx,ip=xx.xx.xx.xx/24,hwaddr=02:00:be:0f:f2:63"

**Comment by ferdl9999** [comment]
Same result, just another string for net0. But the string is correct. It's the same as i am using it in your php api: https://pastebin.com/Md95dN5T

**Comment by ferdl9999** [comment]
Hello,

could you re-produce this issue? Or is it working on your side?
For the case it's working, could you please tell me what i am doing wrong?

Best Regards

**Comment by franklupo** [comment]
Hi,
use **URLEncoder.encode**.

```java
netN.put(1, URLEncoder.encode("name=eth0,rate=15,bridge=vmbr0,firewall=1,gw=xx.xx.xx.xx,ip=xx.xx.xx.xx/24,hwaddr=02:00:be:0f:f2:63",StandardCharsets.UTF_8));
```

**Comment by ferdl9999** [comment]
Thank you! It's working now :)
