### ISSUE TITLE
Don't manage to create QEMU VM

### ISSUE THREAD

**Issue by danielsawan** [Corsinvest/cv4pve-api-java#8]
Hi,

First of all thanks for your java portage. I have a problem when i try to create a VM.
If i call the methode node.getQemu().createVm(vmId) it work with default params. But when i try to customise a little bit i go trought params exceptions.

For example when i try to put a the net[n] parameters i got exception :
```
Map<Integer, String> netN = new HashMap<>();
netN.put(0,URLEncoder.encode("name=eth0,rate=15,bridge=vmbr0,firewall=1,gw=255.255.255.0,ip=192.168.0.1/24,hwaddr=02:00:be:0f:f2:63","utf8"));
```

the error is "Parameter verification failed."

Any help would be appreciated !

**Comment by franklupo** [comment]
Hi,
Renove encode parameter.

Best regards

**Comment by danielsawan** [comment]
Hi

I already tried with and without an encoded param with the same result :/
Another thing i noticed is that when we look at the api we see

[image: image.png]

but on your github the only example we can see is

netN.put(1, URLEncoder.encode("name=eth0,rate=15

Can you please tell me from where come the "name" arg here ?


Thanks for your help !


Le dim. 27 févr. 2022 à 13:24, Daniele Corsini ***@***.***> a
écrit :

**Comment by franklupo** [comment]
HI,
see #7 same problem

**Comment by danielsawan** [comment]
Hi, thanks for your answer. I set the debug lvl to 99 and here is what i get

```
Method: POST , Url: https://192.168.1.72:8006/api2/json/nodes/vpsdev1/qemu
Parameters:
net0 : name%3Deth0%2Crate%3D15%2Cbridge%3Dvmbr0%2Cfirewall%3D1%2Cgw%3D192.168.1.254%2Cip%3D255.255.255.0%2F24%2Chwaddr%3D02%3A00%3Abe%3A0f%3Af2%3A63
cores : 1
sockets : 1
vmid : 100
memory : 2048
storage : local
shares : 1024
balloon : 1024
ostype : l26
```

```
StatusCode:          400
ReasonPhrase:        Parameter verification failed.
IsSuccessStatusCode: false
```

When i remove the net declaration the VPS is created.
Maybe my UTF-8 encode don't do the job ??

**Comment by franklupo** [comment]
investigated the problem

bets regards

**Comment by franklupo** [comment]
please add java code from creation vm with all parameter used.

best reagrds

**Comment by franklupo** [comment]
Hi,
user StandardCharsets.UTF_8 or "UTF-8" not "utf8"

**Comment by franklupo** [comment]
news?

**Comment by danielsawan** [comment]
Ok this work :

Map<Integer, String> netN = new HashMap<>();
netN.put(0, "virtio=xxxxxx,bridge=vmbr0,firewall=1");

**Comment by franklupo** [comment]
Good
