### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by danielsawan** [Corsinvest/cv4pve-api-java#9]
### What happened?

Hi,

I am opening a connection using vp4pve-api-java to my proxmox server. This connection is maintained for multi requests purposes.

After a day, each request returns an empty "data" JSON field as if there is no communication anymore.

I feel like the connection to the proxmox server goes timeout and there is no reconnection process included in the API nor a disconnect / logout method.

I would like to keep the connection open to increase performance.

Do you have any idea to help me solve this problem? 

Thanks for any help you can provide.

### Expected behavior

The connection is renewed or at least give us the possibility to disconnect and reconnect manually.

### Relevant log output

```shell
org.json.JSONException: JSONObject["data"] not found.
```

### Java Version

SE 8

### Proxmox VE Version

7.2

### Version (bug)

v7.1.0

### On what operating system are you experiencing the issue?

Linux

### Pull Request

- [ ] I would like to do a Pull Request

**Comment by franklupo** [comment]
Hi,
the ticket expire.
See documentation https://pve.proxmox.com/wiki/Proxmox_VE_API#Example:_Get_a_New_Ticket_and_the_CSRF_Prevention_Token

In alternative you can use the API token https://pve.proxmox.com/wiki/Proxmox_VE_API#API_Tokens

```java
client.setApiToken("USER@REALM!TOKENID=UUID")

//command without login
System.out.println(client.getVersion().version().getResponse().get("data"));
```

**Comment by danielsawan** [comment]
You mean using the setApiToken instead of login ?

**Comment by franklupo** [comment]
Yes

**Comment by danielsawan** [comment]
I created a permission in the DATACENTER proxmox page but i still get 401 errors on requests.
I went into the source code and i saw something that can be the cause

![sourcecode](https://i.imgur.com/6hnKLFG.pngg)

in the docs they say
```
PVEAPIToken=USER@REALM!TOKENID=UUID
```

but in the source code of the api i read

```
httpCon.setRequestProperty("Authorization", "PVEAPIToken " + _apiToken); // is there the "=" missing ?
```
